export const GET_ALL_COUNTRYS = "GET_ALL_COUNTRYS";
export const CLEAR_COUNTRY_FILTERS = "CLEAR_COUNTRY_FILTERS";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const GET_COUNTRY_BY_NAME = "GET_DOG_BY_NAME";

export const FILTER_BY_CONTINENTS = "FILTER_BY_CONTINENTS";
export const GET_COUNTRY_CONTINENTS = "GET_COUNTRY_CONTINENTS";
export const FILTER_CREATED = "FILTER_CREATED";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_AREA = "ORDER_BY_AREA";
